export const KP_ELEMENT_DEFS = {
    PHOTO: {
        label: 'Foto',
        icon: 'fa-image',
        defaultSize_mm: { w: 80, h: 60 },
        defaultStyle: {
            border_radius_mm: 3,
            object_fit: 'cover',
            focal_point: { x: 0.5, y: 0.5 },
            brightness: 100,
            contrast: 100,
        },
        defaultContent: { caption: '' },
        hasAsset: true,
        accept: 'image/*',
    },
    TEXT: {
        label: 'Teks',
        icon: 'fa-text',
        defaultSize_mm: { w: 60, h: 30 },
        defaultStyle: {
            font_family: 'Inter, sans-serif',
            font_size_pt: 14,
            font_weight: 600,
            color: '#0f172a',
            align: 'left',
            line_height: 1.3,
        },
        defaultContent: { text: 'Klik dua kali untuk edit teks.' },
        editable: true,
    },
    CALENDAR_GRID: {
        label: 'Grid Tanggal',
        icon: 'fa-calendar-days',
        defaultSize_mm: { w: 170, h: 110 },
        defaultStyle: {
            font_family: 'Inter, sans-serif',
            font_size_pt: 10,
            header_color: '#305a49',
            weekend_bg: '#f1f5f3',
            grid_line_color: '#e2e8f0',
        },
        defaultContent: { show_weekend: true, show_month_label: false },
        bindsMonth: true,
    },
    MONTHLY_STATS: {
        label: 'Stat Bulanan',
        icon: 'fa-chart-simple',
        defaultSize_mm: { w: 85, h: 55 },
        defaultStyle: {
            background: '#0f172a',
            accent: '#ccff00',
            text_color: '#ffffff',
            font_family: 'Inter, sans-serif',
        },
        defaultContent: {
            total_km: 0,
            total_runs: 0,
            total_hours: 0,
            longest_run_km: 0,
        },
        bindsMonth: true,
    },
    MONTHLY_GOAL: {
        label: 'Target Bulanan',
        icon: 'fa-bullseye',
        defaultSize_mm: { w: 60, h: 60 },
        defaultStyle: {
            accent: '#ccff00',
            track_bg: '#334155',
            text_color: '#0f172a',
            show_percent: true,
        },
        defaultContent: {
            goal_type: 'mileage',
            target_value: 0,
            current_value: 0,
            unit: 'km',
        },
        bindsMonth: true,
    },
    NOTES: {
        label: 'Catatan',
        icon: 'fa-note-sticky',
        defaultSize_mm: { w: 55, h: 55 },
        defaultStyle: {
            background: '#f1f5f3',
            color: '#0f172a',
            font_family: 'Inter, sans-serif',
            font_size_pt: 10,
        },
        defaultContent: {
            text: "Catatan bulan ini:\n•\n•\n•",
        },
        editable: true,
    },
};
