(function(){
function idSuffix(inst, base){return inst? base+"-"+inst: base}
function initAll(){document.querySelectorAll('.rungo-wrapper').forEach(function(w){initInstance(w)})}
function toRad(deg){return deg*Math.PI/180}
function haversineDistance(lat1, lon1, lat2, lon2){var R=6371000;var dLat=toRad(lat2-lat1);var dLon=toRad(lon2-lon1);var a=Math.sin(dLat/2)*Math.sin(dLat/2)+Math.cos(toRad(lat1))*Math.cos(toRad(lat2))*Math.sin(dLon/2)*Math.sin(dLon/2);var c=2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a));return R*c}
function parsePaceToSeconds(p){if(!p)return null;var parts=p.trim().split(':');if(parts.length!==2)return null;var m=parseInt(parts[0],10);var s=parseInt(parts[1],10);if(isNaN(m)||isNaN(s))return null;return m*60+s}
function computeDistanceKm(points){if(!points||points.length<2)return 0;var dist=0;for(var i=1;i<points.length;i++){var a=points[i-1];var b=points[i];dist+=haversineDistance(a[0],a[1],b[0],b[1])/1000}return dist}
function calcElevationGain(points){if(!points||points.length<2)return 0;var g=0;for(var i=1;i<points.length;i++){var prev=points[i-1][2];var curr=points[i][2];if(prev==null||curr==null||isNaN(prev)||isNaN(curr))continue;var d=curr-prev;if(d>0)g+=d}return g}
function updateElevationChart(inst, points, elevChartRef){if(!window.ApexCharts)return elevChartRef;if(!points||points.length<2){if(elevChartRef){elevChartRef.destroy();elevChartRef=null}var el=document.getElementById(idSuffix(inst,'elev-chart'));if(el)el.innerHTML='';return elevChartRef}
var xs=[];var ys=[];var dist=0;xs.push('0.00');ys.push(points[0][2]||0);for(var i=1;i<points.length;i++){var a=points[i-1];var b=points[i];dist+=haversineDistance(a[0],a[1],b[0],b[1])/1000;xs.push(dist.toFixed(2));ys.push(points[i][2]||0)}
var el=document.getElementById(idSuffix(inst,'elev-chart'));if(elevChartRef){elevChartRef.destroy();elevChartRef=null;el.innerHTML=''}
var options={chart:{type:'area',height:220,toolbar:{show:false},zoom:{enabled:false},animations:{enabled:true,easing:'easeinout',speed:400}},theme:{mode:'light'},stroke:{curve:'smooth',width:2,colors:['#0f766e']},fill:{type:'gradient',gradient:{shadeIntensity:0.2,opacityFrom:0.35,opacityTo:0.05,stops:[0,90,100]}},dataLabels:{enabled:false},grid:{strokeDashArray:3},tooltip:{theme:'light',y:{formatter:function(v){return Math.round(v)+' m'}}},xaxis:{categories:xs,title:{text:'Jarak (km)'},tickAmount:Math.min(xs.length,8),labels:{rotate:0}},yaxis:{title:{text:'Elevasi (m)'}},series:[{name:'Elevasi (m)',data:ys}]}
elevChartRef=new ApexCharts(el,options);elevChartRef.render();return elevChartRef}
 function initInstance(wrapper){var inst=wrapper.getAttribute('data-instance')||'';var MAPBOX_TOKEN='';var MAPBOX_STYLE='mapbox/streets-v12';var map=L.map(idSuffix(inst,'map'),{zoomControl:true}).setView([-6.2,106.8],13);var tileUrl,tileOptions;if(MAPBOX_TOKEN){tileUrl='https://api.mapbox.com/styles/v1/'+MAPBOX_STYLE+'/tiles/{z}/{x}/{y}?access_token='+MAPBOX_TOKEN;tileOptions={tileSize:512,zoomOffset:-1,maxZoom:20,attribution:'© <a href="https://www.openstreetmap.org/">OpenStreetMap</a> © <a href="https://www.mapbox.com/">Mapbox</a>'}}else{tileUrl='https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png';tileOptions={maxZoom:18,attribution:'© OpenStreetMap contributors'}}L.tileLayer(tileUrl,tileOptions).addTo(map);map.createPane('route-arrows');map.getPane('route-arrows').style.zIndex='650'
 var points=[];var polyline=null;var routeDecorator=null;var modeViewOnly=false;var followRoads=true;var showRouteArrows=true;var elevGain=0;var elevChart=null;var clickHistory=[];var redoStack=[];var clickMarkers=[]
var pointIcon=L.divIcon({className:'rungo-marker',html:'<i class="bi bi-geo-alt-fill" style="font-size:20px;color:#0f766e;"></i>',iconSize:[20,20],iconAnchor:[10,20]})
var paramsAll=new URLSearchParams(window.location.search);
var hasRouteParam=paramsAll.has('route');
var hasRidParam=paramsAll.has('rid');
var hasSharedRoute=(hasRouteParam||hasRidParam);
var routeLoaded=false;
 var distanceDisplay=document.getElementById(idSuffix(inst,'distance-display'));var elevDisplay=document.getElementById(idSuffix(inst,'elev-display'));var modeTag=document.getElementById(idSuffix(inst,'mode-tag'));var shareBtn=document.getElementById(idSuffix(inst,'share-btn'));var resetBtn=document.getElementById(idSuffix(inst,'reset-btn'));var undoBtn=document.getElementById(idSuffix(inst,'undo-btn'));var redoBtn=document.getElementById(idSuffix(inst,'redo-btn'));var shareOutput=document.getElementById(idSuffix(inst,'share-output'));var shareUrlInput=document.getElementById(idSuffix(inst,'share-url'));var shareStatus=document.getElementById(idSuffix(inst,'share-status'));var followRoadsCheckbox=document.getElementById(idSuffix(inst,'follow-roads'));var routeArrowsToggle=document.getElementById(idSuffix(inst,'route-arrows-toggle'));var searchInput=document.getElementById(idSuffix(inst,'search-input'));var searchBtn=document.getElementById(idSuffix(inst,'search-btn'));var searchStatus=document.getElementById(idSuffix(inst,'search-status'));var paceInput=document.getElementById(idSuffix(inst,'pace-input'));var hrInput=document.getElementById(idSuffix(inst,'hr-input'));var deviceSelect=document.getElementById(idSuffix(inst,'device-select'));var stravaBtn=document.getElementById(idSuffix(inst,'strava-btn'));var stravaStatus=document.getElementById(idSuffix(inst,'strava-status'));var stravaAuthBtn=document.getElementById(idSuffix(inst,'strava-auth-btn'));var nameInput=document.getElementById(idSuffix(inst,'name-input'));var startInput=document.getElementById(idSuffix(inst,'start-input'));var cadenceInput=document.getElementById(idSuffix(inst,'cadence-input'))
var stravaFormPanel=document.getElementById('strava-form-panel');
if(followRoadsCheckbox){followRoadsCheckbox.addEventListener('change',function(e){followRoads=e.target.checked})}
 if(routeArrowsToggle){showRouteArrows=routeArrowsToggle.checked;routeArrowsToggle.addEventListener('change',function(e){showRouteArrows=e.target.checked;redrawPolyline()})}
function updateUndoRedoButtons(){if(undoBtn)undoBtn.disabled=clickHistory.length===0||modeViewOnly;if(redoBtn)redoBtn.disabled=redoStack.length===0||modeViewOnly}
async function fetchElevations(arr){if(!arr||arr.length===0)return;var BATCH_SIZE=100;for(var start=0;start<arr.length;start+=BATCH_SIZE){var batch=arr.slice(start,start+BATCH_SIZE);var batchIndices=[];var locations=batch.map(function(p,idx){batchIndices.push(start+idx);return{latitude:p[0],longitude:p[1]}});try{var url='https://api.open-elevation.com/api/v1/lookup';var resp=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({locations:locations})});if(!resp.ok)throw new Error('HTTP '+resp.status);var data=await resp.json();if(data.results&&data.results.length===batch.length){for(var i=0;i<batch.length;i++){var originalIdx=batchIndices[i];arr[originalIdx][2]=data.results[i].elevation}}}catch(err){for(var j=0;j<batch.length;j++){var originalIdx2=batchIndices[j];if(arr[originalIdx2][2]==null)arr[originalIdx2][2]=0}}}}
async function updateDistanceAndElevation(){if(points.length<2){distanceDisplay.textContent='0.00 km';elevDisplay.textContent='0 m';if(elevChart){elevChart.destroy();elevChart=null}return}else{var total=0;for(var i=1;i<points.length;i++){var a=points[i-1];var b=points[i];total+=haversineDistance(a[0],a[1],b[0],b[1])}var km=total/1000;distanceDisplay.textContent=km.toFixed(2)+' km'}var needsElevation=points.some(function(p){return p[2]==null||p[2]===undefined});if(needsElevation){await fetchElevations(points)}elevGain=calcElevationGain(points);elevDisplay.textContent=Math.round(elevGain)+' m';elevChart=updateElevationChart(inst,points,elevChart)}
 function redrawPolyline(){if(polyline){map.removeLayer(polyline)}if(routeDecorator){map.removeLayer(routeDecorator);routeDecorator=null}if(points.length>0){var latLngPoints=points.map(function(p){return[p[0],p[1]]});polyline=L.polyline(latLngPoints,{weight:5,color:'#0f766e'}).addTo(map);updateRouteArrows()}}
 function updateRouteArrows(){try{if(!window.L||!window.L.polylineDecorator){var s=document.getElementById('polyline-decorator-script');if(!s){s=document.createElement('script');s.id='polyline-decorator-script';s.src='https://unpkg.com/leaflet-polylinedecorator@1.7.0/dist/leaflet.polylineDecorator.min.js';s.onload=function(){updateRouteArrows()};document.head.appendChild(s)}return}if(!polyline)return;if(routeDecorator){map.removeLayer(routeDecorator);routeDecorator=null}if(!showRouteArrows){return}routeDecorator=L.polylineDecorator(polyline,{patterns:[{offset:20,repeat:60,symbol:L.Symbol.arrowHead({pixelSize:10,polygon:true,pathOptions:{pane:'route-arrows',color:'#dc2626',fillColor:'#dc2626',weight:2,fillOpacity:1}})}]});routeDecorator.addTo(map)}catch(e){}}
function addClickMarker(latlng){var marker=L.marker(latlng,{icon:pointIcon,draggable:true}).addTo(map);marker.pointIndex=points.length-1;marker.on('dragend',function(ev){if(modeViewOnly)return;var ll=ev.target.getLatLng();var idx=ev.target.pointIndex;if(typeof idx==='number'&&idx>=0&&idx<points.length){points[idx]=[ll.lat,ll.lng,points[idx][2]];redrawPolyline();updateDistanceAndElevation();}});clickMarkers.push(marker);return marker}
function removeLastMarker(){var marker=clickMarkers.pop();if(marker){map.removeLayer(marker)}}
function clearAllMarkers(){clickMarkers.forEach(function(m){map.removeLayer(m)});clickMarkers=[]}
function setMode(viewOnly){modeViewOnly=viewOnly;if(viewOnly){modeTag.textContent='Mode: lihat rute (view only)';modeTag.style.background='#dcfce7';resetBtn.disabled=true;followRoadsCheckbox.disabled=true;try{if(resetBtn)resetBtn.style.display='none';if(undoBtn)undoBtn.style.display='none';if(redoBtn)redoBtn.style.display='none';if(shareBtn)shareBtn.style.display='inline-flex'}catch(_){} }else{modeTag.textContent='Mode: edit rute';modeTag.style.background='#f9fafb';resetBtn.disabled=false;followRoadsCheckbox.disabled=false;try{if(resetBtn)resetBtn.style.display='inline-flex';if(undoBtn)undoBtn.style.display='inline-flex';if(redoBtn)redoBtn.style.display='inline-flex';if(shareBtn)shareBtn.style.display='inline-flex'}catch(_){} }updateUndoRedoButtons()}
async function loadRouteFromUrl(){var params=new URLSearchParams(window.location.search);var encoded=params.get('route');if(!encoded){setMode(false);return}try{var json=atob(decodeURIComponent(encoded));var data=JSON.parse(json);if(Array.isArray(data)&&data.length){points=data;points=points.map(function(p){if(Array.isArray(p)&&p.length>=2){return[p[0],p[1],(p[2]!=null&&!isNaN(p[2]))?p[2]:undefined]}return p});redrawPolyline();await updateDistanceAndElevation();map.fitBounds(polyline.getBounds(),{padding:[40,40]});try{map.invalidateSize()}catch(e){}setMode(true);try{document.querySelectorAll('.rungo-wrapper .panel').forEach(function(el){el.style.display='none'});document.querySelectorAll('.rungo-wrapper .search-panel, .rungo-wrapper .hint').forEach(function(el){el.style.display='none'});var infoGroup=document.querySelector('.rungo-wrapper .info-group');if(infoGroup){infoGroup.style.display='flex'}}catch(e){}if(points.length>0){var first=points[0];var lastp=points[points.length-1];try{if(window.L){window.L.marker([first[0],first[1]],{icon:window.L.divIcon({className:'rungo-marker',html:'<i class="bi bi-flag-fill" style="font-size:20px;color:#16a34a;"></i>',iconSize:[20,20],iconAnchor:[10,20]})}).addTo(map);window.L.marker([lastp[0],lastp[1]],{icon:window.L.divIcon({className:'rungo-marker',html:'<i class="bi bi-flag-fill" style="font-size:20px;color:#dc2626;"></i>',iconSize:[20,20],iconAnchor:[10,20]})}).addTo(map)}}catch(e){}}}else{setMode(false)}}catch(err){setMode(false)}}
async function loadRouteById(){var params=new URLSearchParams(window.location.search);var rid=params.get('rid');if(!rid){return false}try{var resp=await fetch(window.location.origin+'/wp-admin/admin-ajax.php?action=rungo_resolve_shortlink&rid='+encodeURIComponent(rid));if(!resp.ok)return false;var data=await resp.json();if(!data||!data.ok||!data.route)return false;var json=atob(decodeURIComponent(data.route));var arr=JSON.parse(json);if(Array.isArray(arr)&&arr.length){points=arr;points=points.map(function(p){if(Array.isArray(p)&&p.length>=2){return[p[0],p[1],(p[2]!=null&&!isNaN(p[2]))?p[2]:undefined]}return p});redrawPolyline();await updateDistanceAndElevation();map.fitBounds(polyline.getBounds(),{padding:[40,40]});try{map.invalidateSize()}catch(e){}setMode(true);try{var formPanel=document.getElementById('strava-btn');if(formPanel){var sec=formPanel.closest('section');if(sec)sec.style.display='none'}document.querySelectorAll('.rungo-wrapper .search-panel, .rungo-wrapper .hint').forEach(function(el){el.style.display='none'});var infoGroup=document.querySelector('.rungo-wrapper .info-group');if(infoGroup){infoGroup.style.display='flex'}}catch(e){}if(points.length>0){var first=points[0];var lastp=points[points.length-1];try{if(window.L){window.L.marker([first[0],first[1]],{icon:window.L.divIcon({className:'rungo-marker',html:'<i class="bi bi-flag-fill" style="font-size:20px;color:#16a34a;"></i>',iconSize:[20,20],iconAnchor:[10,20]})}).addTo(map);window.L.marker([lastp[0],lastp[1]],{icon:window.L.divIcon({className:'rungo-marker',html:'<i class="bi bi-flag-fill" style="font-size:20px;color:#dc2626;"></i>',iconSize:[20,20],iconAnchor:[10,20]})}).addTo(map)}}catch(e){}}return true}return false}catch(e){return false}}
if(!loadRouteById()){loadRouteFromUrl();}
try{map.invalidateSize()}catch(e){}
if(navigator.geolocation&&!modeViewOnly&&!hasSharedRoute){navigator.geolocation.getCurrentPosition(function(pos){var latitude=pos.coords.latitude;var longitude=pos.coords.longitude;map.setView([latitude,longitude],14);L.marker([latitude,longitude],{icon:pointIcon}).addTo(map)},function(){},{enableHighAccuracy:true,timeout:8000})}
async function getRoadSegment(startLat,startLon,endLat,endLon){var url='https://router.project-osrm.org/route/v1/foot/'+(startLon+','+startLat+';'+endLon+','+endLat)+'?overview=full&geometries=geojson';var resp=await fetch(url);if(!resp.ok)throw new Error('OSRM HTTP '+resp.status);var data=await resp.json();if(!data.routes||!data.routes[0]||!data.routes[0].geometry||!data.routes[0].geometry.coordinates)throw new Error('OSRM response tidak valid');var coords=data.routes[0].geometry.coordinates;return coords.map(function(c){return[c[1],c[0]]})}
map.on('click',async function(e){if(modeViewOnly)return;var newPoint=[e.latlng.lat,e.latlng.lng,undefined];var addedPoints=[];if(points.length===0||!followRoads){points.push(newPoint);addedPoints=[newPoint]}else{var last=points[points.length-1];try{var seg=await getRoadSegment(last[0],last[1],newPoint[0],newPoint[1]);for(var i=1;i<seg.length;i++){var pt=seg[i];points.push([pt[0],pt[1],undefined])}addedPoints=seg.slice(1).map(function(pt){return[pt[0],pt[1],undefined]})}catch(err){points.push(newPoint);addedPoints=[newPoint]}}addClickMarker(e.latlng);clickHistory.push({pointsAdded:addedPoints,markerLatLng:e.latlng});redoStack=[];redrawPolyline();await updateDistanceAndElevation();updateUndoRedoButtons()})
if(undoBtn){undoBtn.addEventListener('click',async function(){if(modeViewOnly||clickHistory.length===0)return;var last=clickHistory.pop();var removeCount=last.pointsAdded.length;if(removeCount>0){points.splice(points.length-removeCount,removeCount)}redoStack.push(last);removeLastMarker();redrawPolyline();await updateDistanceAndElevation();updateUndoRedoButtons()})}
if(redoBtn){redoBtn.addEventListener('click',async function(){if(modeViewOnly||redoStack.length===0)return;var action=redoStack.pop();points=points.concat(action.pointsAdded);addClickMarker(action.markerLatLng);clickHistory.push(action);redrawPolyline();await updateDistanceAndElevation();updateUndoRedoButtons()})}
 if(resetBtn){resetBtn.addEventListener('click',async function(){if(modeViewOnly)return;points=[];if(polyline){map.removeLayer(polyline);polyline=null}if(routeDecorator){map.removeLayer(routeDecorator);routeDecorator=null}clickHistory=[];redoStack=[];clearAllMarkers();await updateDistanceAndElevation();if(shareOutput)shareOutput.style.display='none';updateUndoRedoButtons()})}
if(shareBtn){shareBtn.addEventListener('click',async function(){if(points.length<2){alert('Buat dulu rute minimal 2 titik di peta.');return}try{var json=JSON.stringify(points);var encoded=encodeURIComponent(btoa(json));var shortResp=await fetch(window.location.origin+'/wp-admin/admin-ajax.php?action=rungo_create_shortlink',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'route='+encoded});var url='';if(shortResp.ok){var sd=await shortResp.json();if(sd&&sd.ok&&sd.url){url=sd.url}}if(!url){url=window.location.origin+window.location.pathname+'?route='+encoded}if(shareOutput)shareOutput.style.display='flex';if(shareUrlInput)shareUrlInput.value=url;if(shareStatus)shareStatus.textContent='';if(navigator.clipboard&&navigator.clipboard.writeText){navigator.clipboard.writeText(url).then(function(){if(shareStatus)shareStatus.textContent='Link sudah disalin ke clipboard.'}).catch(function(){if(shareStatus)shareStatus.textContent='Salin manual jika perlu.'})}else{if(shareStatus)shareStatus.textContent='Salin manual jika perlu.'}}catch(err){alert('Terjadi error saat membuat link rute.')}})}
async function searchLocation(q){var s=q.trim();if(!s)return;searchStatus.textContent='Mencari...';try{var url='https://nominatim.openstreetmap.org/search?format=json&limit=1&q='+encodeURIComponent(s);var resp=await fetch(url,{headers:{'Accept-Language':'id'}});if(!resp.ok)throw new Error('HTTP '+resp.status);var data=await resp.json();if(!data||data.length===0){searchStatus.textContent='Lokasi tidak ditemukan.';return}var item=data[0];var lat=parseFloat(item.lat);var lon=parseFloat(item.lon);map.setView([lat,lon],14);L.popup().setLatLng([lat,lon]).setContent(item.display_name||s).openOn(map);searchStatus.textContent=''}catch(err){searchStatus.textContent='Gagal mencari lokasi.'}}
if(searchBtn){searchBtn.addEventListener('click',function(){searchLocation(searchInput.value)})}
if(searchInput){searchInput.addEventListener('keydown',function(e){if(e.key==='Enter'){searchLocation(searchInput.value)}})}
var WP_AJAX=window.location.origin+'/wp-admin/admin-ajax.php'
if(!(window.ENABLE_STRAVA_EXPORT===false)){try{fetch(WP_AJAX+'?action=rungo_strava_status',{credentials:'same-origin'}).then(function(r){if(!r.ok)return;return r.json()}).then(function(d){if(d&&d.ok&&d.connected){if(stravaAuthBtn)stravaAuthBtn.style.display='none';if(stravaFormPanel){stravaFormPanel.removeAttribute('style');stravaFormPanel.style.display='flex'}var accEl=document.getElementById('cfgCollapse');if(accEl){accEl.classList.add('show')}var stravaDisconnectBtn=document.getElementById('strava-disconnect-btn');if(stravaDisconnectBtn)stravaDisconnectBtn.style.display='inline-flex'}else{var stravaDisconnectBtn=document.getElementById('strava-disconnect-btn');if(stravaDisconnectBtn)stravaDisconnectBtn.style.display='none'}})}catch(e){}}
var acc=document.getElementById('cfgCollapse');if(acc&&window.matchMedia('(max-width: 640px)').matches){acc.classList.remove('show')}
var togglePanelBtn=document.getElementById('toggle-strava-panel-btn');if(togglePanelBtn){togglePanelBtn.addEventListener('click',function(){var el=document.getElementById('cfgCollapse');if(el){el.classList.toggle('show')}})}
if(stravaBtn){stravaBtn.addEventListener('click',async function(){if(points.length<2){stravaStatus.textContent='Buat dulu rute minimal 2 titik';return}var paceVal=paceInput.value.trim();if(!paceVal){stravaStatus.textContent='Isi pace terlebih dulu';return}stravaStatus.textContent='Mengunggah TCX ke Strava...';stravaBtn.disabled=true;try{var body=new URLSearchParams();body.set('points',buildUploadPointsPayload(points));body.set('pace',paceVal);if(hrInput.value)body.set('hr',String(parseInt(hrInput.value,10)||0));body.set('device',deviceSelect.value||'');body.set('name',(nameInput&&nameInput.value)||'RunRoute Export');if(startInput&&startInput.value)body.set('start_time',startInput.value);if(cadenceInput&&cadenceInput.value)body.set('cadence',String(parseInt(cadenceInput.value,10)||0));var pEl=document.getElementById('power-input');if(pEl&&pEl.value)body.set('power',String(parseInt(pEl.value,10)||0));var resp=await fetch(WP_AJAX+'?action=rungo_strava_upload_route',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:body});if(!resp.ok)throw new Error('HTTP '+resp.status);var data=await resp.json();if(data&&data.ok){if(data.url){stravaStatus.innerHTML='<a href="'+data.url+'" target="_blank" rel="noopener">Buka aktivitas di Strava</a>'}else{stravaStatus.textContent='Sukses upload ke Strava'}var m=document.getElementById('export-metrics');if(m&&data.metrics){var as=(data.metrics.avg_speed||0)*3.6;var ms=(data.metrics.max_speed||0)*3.6;m.innerHTML='Avg HR '+(data.metrics.avg_hr||0)+' bpm • Max HR '+(data.metrics.max_hr||0)+' bpm • Avg Speed '+as.toFixed(2)+' km/h • Max Speed '+ms.toFixed(2)+' km/h • Avg Cad '+(data.metrics.avg_run_cadence||0)+' spm • Max Cad '+(data.metrics.max_run_cadence||0)+' spm'}}else{stravaStatus.textContent=(data&&data.error)?('Gagal: '+data.error):'Gagal upload'}}catch(e){stravaStatus.textContent='Gagal upload TCX'}finally{stravaBtn.disabled=false}})}
function isViewOnly(){try{return (typeof modeViewOnly!=='undefined')?modeViewOnly:false}catch(_){return false}}
document.addEventListener('keydown',function(e){if(isViewOnly())return;var isCmd=e.ctrlKey||e.metaKey;if(!isCmd)return;var k=e.key.toLowerCase();if(k==='z'&&!e.shiftKey){if(undoBtn){undoBtn.click();e.preventDefault()}}else if((k==='z'&&e.shiftKey)||k==='y'){if(redoBtn){redoBtn.click();e.preventDefault()}}})
if(stravaAuthBtn){stravaAuthBtn.addEventListener('click',async function(){stravaStatus.textContent='Membuka Strava authorize...';try{var resp=await fetch(WP_AJAX+'?action=rungo_strava_auth_url');if(!resp.ok)throw new Error('HTTP '+resp.status);var data=await resp.json();if(data&&data.url){window.location.href=data.url}else{stravaStatus.textContent='Gagal membuat URL authorize'}}catch(e){stravaStatus.textContent='Gagal membuat URL authorize'}})}

 var stravaDisconnectBtn=document.getElementById('strava-disconnect-btn');
 if(stravaDisconnectBtn){stravaDisconnectBtn.addEventListener('click',async function(){try{var resp=await fetch(WP_AJAX,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},credentials:'same-origin',body:'action=rungo_strava_disconnect'});if(!resp.ok)throw new Error('HTTP '+resp.status);var d=await resp.json();if(d&&d.ok){if(stravaAuthBtn)stravaAuthBtn.style.display='inline-flex';if(stravaFormPanel)stravaFormPanel.style.display='none';var accEl=document.getElementById('cfgCollapse');if(accEl){accEl.classList.remove('show')}stravaDisconnectBtn.style.display='none';var s=document.getElementById('strava-status');if(s)s.textContent='Strava terputus'} }catch(e){var s=document.getElementById('strava-status');if(s)s.textContent='Gagal memutus koneksi'}})}

function buildUploadPointsPayload(arr){return JSON.stringify(arr.map(function(p){return [p[0],p[1],p[2]]}))}

var uploadRouteBtn=document.getElementById(idSuffix(inst,'strava-upload-route-btn'))
function buildGpx(points, startTime, paceSec, cadenceAvg){var pad=function(n){return (n<10?'0':'')+n};var toIso=function(ts){var d=new Date(ts*1000);return d.getUTCFullYear()+'-'+pad(d.getUTCMonth()+1)+'-'+pad(d.getUTCDate())+'T'+pad(d.getUTCHours())+':'+pad(d.getUTCMinutes())+':'+pad(d.getUTCSeconds())+'Z'};var includeTime=Number.isFinite(paceSec)&&paceSec>0;var includeCad=!!(cadenceAvg&&String(cadenceAvg).length>0);var gpx='<?xml version="1.0" encoding="UTF-8"?>\n<gpx version="1.1" creator="RunRoute" xmlns="http://www.topografix.com/GPX/1/1">\n<trk>\n<trkseg>\n';var dist=0;var ts=startTime||Math.floor(Date.now()/1000);var prev=[points[0][0],points[0][1]];gpx+='<trkpt lat="'+points[0][0]+'" lon="'+points[0][1]+'"><ele>'+(points[0][2]||0)+'</ele>'+(includeTime?('<time>'+toIso(ts)+'</time>'):'')+(includeCad?('<Cadence xmlns="">'+parseInt(cadenceAvg,10)+'</Cadence>'):'')+'</trkpt>\n';for(var i=1;i<points.length;i++){var a=prev;var b=[points[i][0],points[i][1]];var dd=haversineDistance(a[0],a[1],b[0],b[1]);dist+=dd;var t=ts+Math.round((dist/1000)*paceSec);gpx+='<trkpt lat="'+b[0]+'" lon="'+b[1]+'"><ele>'+(points[i][2]||0)+'</ele>'+(includeTime?('<time>'+toIso(t)+'</time>'):'')+(includeCad?('<Cadence xmlns="">'+parseInt(cadenceAvg,10)+'</Cadence>'):'')+'</trkpt>\n';prev=b}gpx+='</trkseg>\n</trk>\n</gpx>';return gpx}
if(uploadRouteBtn){uploadRouteBtn.addEventListener('click',function(){if(points.length<2){stravaStatus.textContent='Buat dulu rute minimal 2 titik';return}var paceVal=(paceInput&&paceInput.value||'').trim();var paceSec=null;if(paceVal&&paceVal.includes(':')){var parts=paceVal.split(':');var pm=parseInt(parts[0],10);var ps=parseInt(parts[1],10);if(!isNaN(pm)&&!isNaN(ps)&&pm>=0&&ps>=0){paceSec=pm*60+ps}}var startTs=null;if(paceSec){startTs=Math.floor(Date.now()/1000);if(startInput&&startInput.value){var st=Math.floor(Date.parse(startInput.value)/1000);if(!isNaN(st))startTs=st}}var gpx=buildGpx(points,startTs,paceSec,(cadenceInput&&cadenceInput.value)||'');var blob=new Blob([gpx],{type:'application/gpx+xml'});var a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='runroute.gpx';a.click();setTimeout(function(){URL.revokeObjectURL(a.href)},1000);stravaStatus.textContent='GPX berhasil dibuat' })}

var fileInput=document.getElementById(idSuffix(inst,'file-upload'))
var uploadFileBtn=document.getElementById(idSuffix(inst,'upload-file-btn'))
if(uploadFileBtn){uploadFileBtn.addEventListener('click',async function(){if(!fileInput||!fileInput.files||fileInput.files.length===0){stravaStatus.textContent='Pilih file .gpx/.tcx/.fit dulu';return}var f=fileInput.files[0];var ext=(f.name.split('.').pop()||'').toLowerCase();var dt=(ext==='tcx'||ext==='gpx'||ext==='fit')?ext:'gpx';stravaStatus.textContent='Mengunggah file ke Strava...';try{var fd=new FormData();fd.append('file',f);fd.append('data_type',dt);fd.append('name','RunRoute Upload');fd.append('description','Uploaded via RunRoute');var resp=await fetch(WP_AJAX+'?action=rungo_strava_upload_file',{method:'POST',body:fd});if(!resp.ok)throw new Error('HTTP '+resp.status);var data=await resp.json();if(data&&data.ok){if(data.url){stravaStatus.innerHTML='<a href="'+data.url+'" target="_blank" rel="noopener">Buka aktivitas di Strava</a>'}else{stravaStatus.textContent='Sukses upload ke Strava'}}else{stravaStatus.textContent=(data&&data.error)?('Gagal: '+data.error):'Gagal upload'}}catch(e){stravaStatus.textContent='Gagal upload file'}})}

function parseGpxToPoints(text){try{var doc=new DOMParser().parseFromString(text,'application/xml');var trkpts=doc.getElementsByTagName('trkpt');var arr=[];for(var i=0;i<trkpts.length;i++){var el=trkpts[i];var lat=parseFloat(el.getAttribute('lat'));var lon=parseFloat(el.getAttribute('lon'));var eleEl=el.getElementsByTagName('ele')[0];var ele=eleEl?parseFloat(eleEl.textContent):undefined;if(!isNaN(lat)&&!isNaN(lon))arr.push([lat,lon,ele])}return arr}catch(e){return null}}
function parseTcxToPoints(text){try{var doc=new DOMParser().parseFromString(text,'application/xml');var tps=doc.getElementsByTagName('Trackpoint');var arr=[];for(var i=0;i<tps.length;i++){var tp=tps[i];var pos=tp.getElementsByTagName('Position')[0];if(!pos)continue;var latEl=pos.getElementsByTagName('LatitudeDegrees')[0];var lonEl=pos.getElementsByTagName('LongitudeDegrees')[0];if(!latEl||!lonEl)continue;var lat=parseFloat(latEl.textContent);var lon=parseFloat(lonEl.textContent);var altEl=tp.getElementsByTagName('AltitudeMeters')[0];var ele=altEl?parseFloat(altEl.textContent):undefined;if(!isNaN(lat)&&!isNaN(lon))arr.push([lat,lon,ele])}return arr}catch(e){return null}}
if(fileInput){fileInput.addEventListener('change',function(){if(!fileInput.files||fileInput.files.length===0)return;var f=fileInput.files[0];var ext=(f.name.split('.').pop()||'').toLowerCase();var reader=new FileReader();reader.onload=function(){var text=reader.result;var pts=null;if(ext==='gpx')pts=parseGpxToPoints(text);else if(ext==='tcx')pts=parseTcxToPoints(text);if(pts&&pts.length>1){points=pts;clickHistory=[];redoStack=[];clearAllMarkers();redrawPolyline();updateDistanceAndElevation();map.setView([points[0][0],points[0][1]],14);try{map.invalidateSize()}catch(e){}stravaStatus.textContent='Track dari '+ext+' dimuat'}else{stravaStatus.textContent='Gagal parse file '+ext}};stravaStatus.textContent='Memuat file '+ext+'...';reader.readAsText(f)})}
}
if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',initAll)}else{initAll()}
})();
