<?php

return [

    'goals' => [

        '5K' => [
            [
                'id' => '5k_12x400',
                'goal' => '5K',
                'type' => 'interval',
                'name' => '12 x 400m',
                'focus' => 'Speed endurance',
                'main_set' => '12 reps x 400m',
                'recovery' => '60 to 90 sec easy jog',
                'intensity' => '5K pace or slightly faster',
                'best_for' => 'Building speed endurance',
                'note' => 'Best for improving fast pace control over short repeats.',
            ],
            [
                'id' => '5k_6x800',
                'goal' => '5K',
                'type' => 'interval',
                'name' => '6 x 800m',
                'focus' => 'VO2max',
                'main_set' => '6 reps x 800m',
                'recovery' => '2 min easy jog',
                'intensity' => 'Around 5K effort',
                'best_for' => 'Improving aerobic ceiling',
                'note' => 'Use this when the runner needs stronger VO2max development.',
            ],
            [
                'id' => '5k_5x1k',
                'goal' => '5K',
                'type' => 'interval',
                'name' => '5 x 1K',
                'focus' => 'Race pace',
                'main_set' => '5 reps x 1K',
                'recovery' => '2 min easy jog',
                'intensity' => 'Target 5K pace',
                'best_for' => 'Adapting to 5K race pace',
                'note' => 'Good race-specific session for the build or peak phase.',
            ],
            [
                'id' => '5k_20x200',
                'goal' => '5K',
                'type' => 'repetition',
                'name' => '20 x 200m',
                'focus' => 'Cadence and turnover',
                'main_set' => '20 reps x 200m',
                'recovery' => '200m easy jog',
                'intensity' => 'Fast but relaxed',
                'best_for' => 'Improving running economy',
                'note' => 'Keep the reps smooth. Do not sprint all out.',
            ],
            [
                'id' => '5k_3x1600',
                'goal' => '5K',
                'type' => 'interval',
                'name' => '3 x 1.6K',
                'focus' => 'Pace tolerance',
                'main_set' => '3 reps x 1.6K',
                'recovery' => '3 min easy jog',
                'intensity' => 'Near 5K pace',
                'best_for' => 'Holding fast pace under fatigue',
                'note' => 'Better for intermediate and advanced runners.',
            ],
        ],

        '10K' => [
            [
                'id' => '10k_8x1k',
                'goal' => '10K',
                'type' => 'interval',
                'name' => '8 x 1K',
                'focus' => 'Race pace control',
                'main_set' => '8 reps x 1K',
                'recovery' => '90 sec to 2 min easy jog',
                'intensity' => 'Target 10K pace',
                'best_for' => 'Improving 10K pace stability',
                'note' => 'Main race-specific workout for 10K preparation.',
            ],
            [
                'id' => '10k_5x1200',
                'goal' => '10K',
                'type' => 'interval',
                'name' => '5 x 1.2K',
                'focus' => 'Strength endurance',
                'main_set' => '5 reps x 1.2K',
                'recovery' => '2 min easy jog',
                'intensity' => '10K effort',
                'best_for' => 'Building speed endurance',
                'note' => 'Good bridge between short intervals and longer threshold work.',
            ],
            [
                'id' => '10k_4x2k',
                'goal' => '10K',
                'type' => 'threshold',
                'name' => '4 x 2K',
                'focus' => 'Threshold',
                'main_set' => '4 reps x 2K',
                'recovery' => '2 to 3 min easy jog',
                'intensity' => 'Threshold to 10K effort',
                'best_for' => 'Building lactate threshold',
                'note' => 'Keep the pace controlled. This is not a sprint workout.',
            ],
            [
                'id' => '10k_10x500',
                'goal' => '10K',
                'type' => 'interval',
                'name' => '10 x 500m',
                'focus' => 'Rhythm',
                'main_set' => '10 reps x 500m',
                'recovery' => '90 sec easy jog',
                'intensity' => 'Faster than 10K pace',
                'best_for' => 'Improving rhythm and running economy',
                'note' => 'Useful when the runner needs sharper turnover.',
            ],
            [
                'id' => '10k_3x3k',
                'goal' => '10K',
                'type' => 'threshold',
                'name' => '3 x 3K',
                'focus' => 'Race pressure',
                'main_set' => '3 reps x 3K',
                'recovery' => '3 min easy jog',
                'intensity' => 'Controlled 10K effort',
                'best_for' => 'Preparing for 10K race fatigue',
                'note' => 'Use only when the runner has enough base fitness.',
            ],
        ],

        'HALF_MARATHON' => [
            [
                'id' => 'hm_5x2k',
                'goal' => 'HALF_MARATHON',
                'type' => 'threshold',
                'name' => '5 x 2K',
                'focus' => 'Half marathon pace',
                'main_set' => '5 reps x 2K',
                'recovery' => '2 min easy jog',
                'intensity' => 'Half marathon pace',
                'best_for' => 'Practicing race pace',
                'note' => 'Good race-specific session for half marathon preparation.',
            ],
            [
                'id' => 'hm_4x3k',
                'goal' => 'HALF_MARATHON',
                'type' => 'threshold',
                'name' => '4 x 3K',
                'focus' => 'Stamina',
                'main_set' => '4 reps x 3K',
                'recovery' => '3 min easy jog',
                'intensity' => 'Half marathon pace to threshold effort',
                'best_for' => 'Building half marathon stamina',
                'note' => 'Use in the middle phase of a half marathon block.',
            ],
            [
                'id' => 'hm_3x5k',
                'goal' => 'HALF_MARATHON',
                'type' => 'threshold',
                'name' => '3 x 5K',
                'focus' => 'Race endurance',
                'main_set' => '3 reps x 5K',
                'recovery' => '4 min easy jog',
                'intensity' => 'Controlled half marathon effort',
                'best_for' => 'Improving endurance under fatigue',
                'note' => 'Advanced session. Avoid for beginners.',
            ],
            [
                'id' => 'hm_6x1600',
                'goal' => 'HALF_MARATHON',
                'type' => 'threshold',
                'name' => '6 x 1.6K',
                'focus' => 'Lactate threshold',
                'main_set' => '6 reps x 1.6K',
                'recovery' => '2 min easy jog',
                'intensity' => 'Threshold effort',
                'best_for' => 'Improving sustainable pace',
                'note' => 'Good for improving controlled race effort.',
            ],
            [
                'id' => 'hm_progression_run',
                'goal' => 'HALF_MARATHON',
                'type' => 'progression',
                'name' => 'Progression Run',
                'focus' => 'Finishing strength',
                'main_set' => '3K easy + 6K half marathon pace + 3K faster',
                'recovery' => 'No full recovery',
                'intensity' => 'Progressive effort',
                'best_for' => 'Building strong finish control',
                'note' => 'Use when the runner needs better control late in the race.',
            ],
        ],

        'FULL_MARATHON' => [
            [
                'id' => 'fm_6x2k',
                'goal' => 'FULL_MARATHON',
                'type' => 'threshold',
                'name' => '6 x 2K',
                'focus' => 'Aerobic strength',
                'main_set' => '6 reps x 2K',
                'recovery' => '2 min easy jog',
                'intensity' => 'Threshold to marathon effort',
                'best_for' => 'Building aerobic strength',
                'note' => 'Useful in early to middle marathon training phase.',
            ],
            [
                'id' => 'fm_4x5k',
                'goal' => 'FULL_MARATHON',
                'type' => 'marathon_pace',
                'name' => '4 x 5K',
                'focus' => 'Marathon pace control',
                'main_set' => '4 reps x 5K at marathon pace',
                'recovery' => '1K easy jog',
                'intensity' => 'Marathon pace',
                'best_for' => 'Improving marathon pace control',
                'note' => 'Best for race-specific marathon preparation.',
            ],
            [
                'id' => 'fm_3x6k',
                'goal' => 'FULL_MARATHON',
                'type' => 'marathon_pace',
                'name' => '3 x 6K',
                'focus' => 'Fatigue resistance',
                'main_set' => '3 reps x 6K',
                'recovery' => '1K easy jog',
                'intensity' => 'Marathon pace to steady effort',
                'best_for' => 'Building fatigue resistance',
                'note' => 'Better for intermediate and advanced marathon runners.',
            ],
            [
                'id' => 'fm_long_run_mp_block',
                'goal' => 'FULL_MARATHON',
                'type' => 'long_run_quality',
                'name' => 'Long Run + MP Block',
                'focus' => 'Race simulation',
                'main_set' => 'Long run with 3 x 5K at marathon pace',
                'recovery' => '1K easy jog between blocks',
                'intensity' => 'Easy with marathon pace blocks',
                'best_for' => 'Marathon-specific long run quality',
                'note' => 'Attach this to long run day, not a separate interval day.',
            ],
            [
                'id' => 'fm_fast_finish_long_run',
                'goal' => 'FULL_MARATHON',
                'type' => 'long_run_quality',
                'name' => 'Fast Finish Long Run',
                'focus' => 'Finishing strength',
                'main_set' => 'Long run with last 6 to 8K at marathon pace',
                'recovery' => 'No full recovery',
                'intensity' => 'Easy first, marathon pace finish',
                'best_for' => 'Mental strength and late-race control',
                'note' => 'Use only after the runner has enough endurance base.',
            ],
        ],

    ],

    'default_warm_up' => '10 to 15 min easy run + dynamic drills',

    'default_cool_down' => '10 min easy jog',

    'level_rules' => [
        'beginner' => [
            'max_quality_sessions_per_week' => 1,
            'volume_adjustment' => 0.65,
            'description' => 'Reduce quality workout volume by around 25 to 40 percent.',
        ],
        'intermediate' => [
            'max_quality_sessions_per_week' => 1,
            'volume_adjustment' => 0.85,
            'description' => 'Use moderate workout volume and keep one quality workout per week.',
        ],
        'advanced' => [
            'max_quality_sessions_per_week' => 2,
            'volume_adjustment' => 1.00,
            'description' => 'Use full workout volume if weekly mileage supports it.',
        ],
    ],

    'training_phase_rules' => [
        'base' => [
            'preferred_types' => ['threshold', 'repetition'],
            'description' => 'Focus on easy running, light threshold, strides, and controlled speed.',
        ],
        'build' => [
            'preferred_types' => ['interval', 'threshold', 'progression'],
            'description' => 'Build race-specific fitness with structured quality sessions.',
        ],
        'peak' => [
            'preferred_types' => ['interval', 'threshold', 'marathon_pace', 'long_run_quality'],
            'description' => 'Use race-specific workouts while controlling total fatigue.',
        ],
        'taper' => [
            'preferred_types' => ['repetition', 'interval'],
            'description' => 'Reduce volume but keep light intensity to stay sharp.',
        ],
    ],

];