<?php

return [

    'goals' => [

        '5K' => [
            [
                'id' => '5k_12x400',
                'goal' => '5K',
                'type' => 'interval',
                'name' => '12 x 400m',
                'focus' => 'Speed endurance',
                'main_set' => '12 reps x 400m',
                'recovery' => '60 to 90 sec easy jog',
                'intensity' => '5K pace or slightly faster',
                'best_for' => 'Building speed endurance',
                'note' => 'Best for improving fast pace control over short repeats.',
            ],
            [
                'id' => '5k_6x800',
                'goal' => '5K',
                'type' => 'interval',
                'name' => '6 x 800m',
                'focus' => 'VO2max',
                'main_set' => '6 reps x 800m',
                'recovery' => '2 min easy jog',
                'intensity' => 'Around 5K effort',
                'best_for' => 'Improving aerobic ceiling',
                'note' => 'Use this when the runner needs stronger VO2max development.',
            ],
            [
                'id' => '5k_5x1k',
                'goal' => '5K',
                'type' => 'interval',
                'name' => '5 x 1K',
                'focus' => 'Race pace',
                'main_set' => '5 reps x 1K',
                'recovery' => '2 min easy jog',
                'intensity' => 'Target 5K pace',
                'best_for' => 'Adapting to 5K race pace',
                'note' => 'Good race-specific session for the build or peak phase.',
            ],
            [
                'id' => '5k_20x200',
                'goal' => '5K',
                'type' => 'repetition',
                'name' => '20 x 200m',
                'focus' => 'Cadence and turnover',
                'main_set' => '20 reps x 200m',
                'recovery' => '200m easy jog',
                'intensity' => 'Fast but relaxed',
                'best_for' => 'Improving running economy',
                'note' => 'Keep the reps smooth. Do not sprint all out.',
            ],
            [
                'id' => '5k_3x1600',
                'goal' => '5K',
                'type' => 'interval',
                'name' => '3 x 1.6K',
                'focus' => 'Pace tolerance',
                'main_set' => '3 reps x 1.6K',
                'recovery' => '3 min easy jog',
                'intensity' => 'Near 5K pace',
                'best_for' => 'Holding fast pace under fatigue',
                'note' => 'Better for intermediate and advanced runners.',
            ],
            [
                'id' => '5k_hill_10x30sec',
                'goal' => '5K',
                'type' => 'hill',
                'name' => '10 x 30 Sec Hill Repeats',
                'focus' => 'Muscle power & leg turnover',
                'main_set' => '10 reps x 30 sec uphill',
                'recovery' => 'Walk down slowly',
                'intensity' => 'R pace / 90-95% effort',
                'best_for' => 'Building leg power and running economy',
                'note' => 'Drive knees high, maintain tall posture, and focus on smooth turnover.',
            ],
        ],

        '10K' => [
            [
                'id' => '10k_8x1k',
                'goal' => '10K',
                'type' => 'interval',
                'name' => '8 x 1K',
                'focus' => 'Race pace control',
                'main_set' => '8 reps x 1K',
                'recovery' => '90 sec to 2 min easy jog',
                'intensity' => 'Target 10K pace',
                'best_for' => 'Improving 10K pace stability',
                'note' => 'Main race-specific workout for 10K preparation.',
            ],
            [
                'id' => '10k_5x1200',
                'goal' => '10K',
                'type' => 'interval',
                'name' => '5 x 1.2K',
                'focus' => 'Strength endurance',
                'main_set' => '5 reps x 1.2K',
                'recovery' => '2 min easy jog',
                'intensity' => '10K effort',
                'best_for' => 'Building speed endurance',
                'note' => 'Good bridge between short intervals and longer threshold work.',
            ],
            [
                'id' => '10k_4x2k',
                'goal' => '10K',
                'type' => 'threshold',
                'name' => '4 x 2K',
                'focus' => 'Threshold',
                'main_set' => '4 reps x 2K',
                'recovery' => '2 to 3 min easy jog',
                'intensity' => 'Threshold to 10K effort',
                'best_for' => 'Building lactate threshold',
                'note' => 'Keep the pace controlled. This is not a sprint workout.',
            ],
            [
                'id' => '10k_10x500',
                'goal' => '10K',
                'type' => 'interval',
                'name' => '10 x 500m',
                'focus' => 'Rhythm',
                'main_set' => '10 reps x 500m',
                'recovery' => '90 sec easy jog',
                'intensity' => 'Faster than 10K pace',
                'best_for' => 'Improving rhythm and running economy',
                'note' => 'Useful when the runner needs sharper turnover.',
            ],
            [
                'id' => '10k_3x3k',
                'goal' => '10K',
                'type' => 'threshold',
                'name' => '3 x 3K',
                'focus' => 'Race pressure',
                'main_set' => '3 reps x 3K',
                'recovery' => '3 min easy jog',
                'intensity' => 'Controlled 10K effort',
                'best_for' => 'Preparing for 10K race fatigue',
                'note' => 'Use only when the runner has enough base fitness.',
            ],
            [
                'id' => '10k_hill_8x45sec',
                'goal' => '10K',
                'type' => 'hill',
                'name' => '8 x 45 Sec Hill Repeats',
                'focus' => 'Speed endurance & hill power',
                'main_set' => '8 reps x 45 sec uphill',
                'recovery' => 'Jog down slowly',
                'intensity' => '5K-10K effort',
                'best_for' => 'Building aerobic strength and biomechanical efficiency',
                'note' => 'Maintain consistent power on the incline without over-striding.',
            ],
        ],

        'HALF_MARATHON' => [
            [
                'id' => 'hm_5x2k',
                'goal' => 'HALF_MARATHON',
                'type' => 'threshold',
                'name' => '5 x 2K',
                'focus' => 'Half marathon pace',
                'main_set' => '5 reps x 2K',
                'recovery' => '2 min easy jog',
                'intensity' => 'Half marathon pace',
                'best_for' => 'Practicing race pace',
                'note' => 'Good race-specific session for half marathon preparation.',
            ],
            [
                'id' => 'hm_4x3k',
                'goal' => 'HALF_MARATHON',
                'type' => 'threshold',
                'name' => '4 x 3K',
                'focus' => 'Stamina',
                'main_set' => '4 reps x 3K',
                'recovery' => '3 min easy jog',
                'intensity' => 'Half marathon pace to threshold effort',
                'best_for' => 'Building half marathon stamina',
                'note' => 'Use in the middle phase of a half marathon block.',
            ],
            [
                'id' => 'hm_3x5k',
                'goal' => 'HALF_MARATHON',
                'type' => 'threshold',
                'name' => '3 x 5K',
                'focus' => 'Race endurance',
                'main_set' => '3 reps x 5K',
                'recovery' => '4 min easy jog',
                'intensity' => 'Controlled half marathon effort',
                'best_for' => 'Improving endurance under fatigue',
                'note' => 'Advanced session. Avoid for beginners.',
            ],
            [
                'id' => 'hm_6x1600',
                'goal' => 'HALF_MARATHON',
                'type' => 'threshold',
                'name' => '6 x 1.6K',
                'focus' => 'Lactate threshold',
                'main_set' => '6 reps x 1.6K',
                'recovery' => '2 min easy jog',
                'intensity' => 'Threshold effort',
                'best_for' => 'Improving sustainable pace',
                'note' => 'Good for improving controlled race effort.',
            ],
            [
                'id' => 'hm_progression_run',
                'goal' => 'HALF_MARATHON',
                'type' => 'progression',
                'name' => 'Progression Run',
                'focus' => 'Finishing strength',
                'main_set' => '3K easy + 6K half marathon pace + 3K faster',
                'recovery' => 'No full recovery',
                'intensity' => 'Progressive effort',
                'best_for' => 'Building strong finish control',
                'note' => 'Use when the runner needs better control late in the race.',
            ],
            [
                'id' => 'hm_hill_6x60sec',
                'goal' => 'HALF_MARATHON',
                'type' => 'hill',
                'name' => '6 x 60 Sec Hill Repeats',
                'focus' => 'Stamina & hill strength',
                'main_set' => '6 reps x 60 sec uphill',
                'recovery' => 'Jog down slowly',
                'intensity' => '10K to HM effort',
                'best_for' => 'Building stamina and fatigue resistance',
                'note' => 'Drive steadily up the incline with controlled rhythm.',
            ],
        ],

        'FULL_MARATHON' => [
            [
                'id' => 'fm_6x2k',
                'goal' => 'FULL_MARATHON',
                'type' => 'threshold',
                'name' => '6 x 2K',
                'focus' => 'Aerobic strength',
                'main_set' => '6 reps x 2K',
                'recovery' => '2 min easy jog',
                'intensity' => 'Threshold to marathon effort',
                'best_for' => 'Building aerobic strength',
                'note' => 'Useful in early to middle marathon training phase.',
            ],
            [
                'id' => 'fm_4x5k',
                'goal' => 'FULL_MARATHON',
                'type' => 'marathon_pace',
                'name' => '4 x 5K',
                'focus' => 'Marathon pace control',
                'main_set' => '4 reps x 5K at marathon pace',
                'recovery' => '1K easy jog',
                'intensity' => 'Marathon pace',
                'best_for' => 'Improving marathon pace control',
                'note' => 'Best for race-specific marathon preparation.',
            ],
            [
                'id' => 'fm_3x6k',
                'goal' => 'FULL_MARATHON',
                'type' => 'marathon_pace',
                'name' => '3 x 6K',
                'focus' => 'Fatigue resistance',
                'main_set' => '3 reps x 6K',
                'recovery' => '1K easy jog',
                'intensity' => 'Marathon pace to steady effort',
                'best_for' => 'Building fatigue resistance',
                'note' => 'Better for intermediate and advanced marathon runners.',
            ],
            [
                'id' => 'fm_long_run_mp_block',
                'goal' => 'FULL_MARATHON',
                'type' => 'long_run_quality',
                'name' => 'Long Run + MP Block',
                'focus' => 'Race simulation',
                'main_set' => 'Long run with 3 x 5K at marathon pace',
                'recovery' => '1K easy jog between blocks',
                'intensity' => 'Easy with marathon pace blocks',
                'best_for' => 'Marathon-specific long run quality',
                'note' => 'Attach this to long run day, not a separate interval day.',
            ],
            [
                'id' => 'fm_fast_finish_long_run',
                'goal' => 'FULL_MARATHON',
                'type' => 'long_run_quality',
                'name' => 'Fast Finish Long Run',
                'focus' => 'Finishing strength',
                'main_set' => 'Long run with last 6 to 8K at marathon pace',
                'recovery' => 'No full recovery',
                'intensity' => 'Easy first, marathon pace finish',
                'best_for' => 'Mental strength and late-race control',
                'note' => 'Use only after the runner has enough endurance base.',
            ],
            [
                'id' => 'fm_hill_6x90sec',
                'goal' => 'FULL_MARATHON',
                'type' => 'hill',
                'name' => '6 x 90 Sec Hill Repeats',
                'focus' => 'Aerobic power & fatigue resistance',
                'main_set' => '6 reps x 90 sec uphill',
                'recovery' => 'Walk or jog down',
                'intensity' => 'Threshold to 10K effort',
                'best_for' => 'Leg strength and aerobic power for marathon endurance',
                'note' => 'Maintain steady rhythm throughout each repeat.',
            ],
        ],

    ],

    'default_warm_up' => '10 to 15 min easy run + dynamic drills',

    'default_cool_down' => '10 min easy jog',

    'level_rules' => [
        'beginner' => [
            'max_quality_sessions_per_week' => 1,
            'volume_adjustment' => 0.65,
            'description' => 'Reduce quality workout volume by around 25 to 40 percent.',
        ],
        'intermediate' => [
            'max_quality_sessions_per_week' => 1,
            'volume_adjustment' => 0.85,
            'description' => 'Use moderate workout volume and keep one quality workout per week.',
        ],
        'advanced' => [
            'max_quality_sessions_per_week' => 2,
            'volume_adjustment' => 1.00,
            'description' => 'Use full workout volume if weekly mileage supports it.',
        ],
    ],

    'training_phase_rules' => [
        'base' => [
            'preferred_types' => ['threshold', 'repetition', 'hill'],
            'description' => 'Focus on easy running, light threshold, strides, hill repeats, and controlled speed.',
        ],
        'build' => [
            'preferred_types' => ['interval', 'threshold', 'progression', 'hill'],
            'description' => 'Build race-specific fitness with structured quality sessions.',
        ],
        'peak' => [
            'preferred_types' => ['interval', 'threshold', 'marathon_pace', 'long_run_quality'],
            'description' => 'Use race-specific workouts while controlling total fatigue.',
        ],
        'taper' => [
            'preferred_types' => ['repetition', 'interval'],
            'description' => 'Reduce volume but keep light intensity to stay sharp.',
        ],
    ],
    
    'COOPER_12_MIN_GENERAL' => [
    [
        'id' => 'cooper12_8x400_target_pace',
        'goal' => 'COOPER_12_MIN_GENERAL',
        'type' => 'interval',
        'name' => '8 x 400m Target Pace',
        'focus' => 'Specific 12-minute pace control',
        'main_set' => '8 reps x 400m',
        'recovery' => '60 to 90 sec easy jog',
        'intensity' => '3200m target: 90 sec per 400m, 3400m target: 84 to 85 sec per 400m',
        'best_for' => 'Learning exact rhythm for 3200m to 3400m Cooper test',
        'note' => 'This is the safest core workout for general runners. Do not sprint the first reps.',
    ],
    [
        'id' => 'cooper12_10x300_fast_relaxed',
        'goal' => 'COOPER_12_MIN_GENERAL',
        'type' => 'repetition',
        'name' => '10 x 300m Fast Relaxed',
        'focus' => 'Leg speed and running economy',
        'main_set' => '10 reps x 300m',
        'recovery' => '100m walk or 200m easy jog',
        'intensity' => 'Faster than target pace but relaxed',
        'best_for' => 'Improving cadence, turnover, and smooth speed',
        'note' => 'Use this when the runner feels heavy and needs sharper mechanics without too much fatigue.',
    ],
    [
        'id' => 'cooper12_5x600_overpace',
        'goal' => 'COOPER_12_MIN_GENERAL',
        'type' => 'interval',
        'name' => '5 x 600m Overpace',
        'focus' => 'VO2max and speed endurance',
        'main_set' => '5 reps x 600m',
        'recovery' => '2 min easy jog',
        'intensity' => 'Slightly faster than 12-minute target pace',
        'best_for' => 'Making target pace feel more manageable',
        'note' => 'Good for build phase. Stop if pace drops badly after rep 3.',
    ],
    [
        'id' => 'cooper12_6x800_target_effort',
        'goal' => 'COOPER_12_MIN_GENERAL',
        'type' => 'interval',
        'name' => '6 x 800m Target Effort',
        'focus' => 'VO2max durability',
        'main_set' => '6 reps x 800m',
        'recovery' => '2 to 2.5 min easy jog',
        'intensity' => '3200m target: around 3:00 per 800m, 3400m target: around 2:49 to 2:50 per 800m',
        'best_for' => 'Building the engine needed for 12-minute maximal running',
        'note' => 'This is harder than 400m repeats. Use only after 2 to 3 weeks of consistent running.',
    ],
    [
        'id' => 'cooper12_4x1000_controlled',
        'goal' => 'COOPER_12_MIN_GENERAL',
        'type' => 'interval',
        'name' => '4 x 1K Controlled',
        'focus' => 'Race-specific endurance',
        'main_set' => '4 reps x 1K',
        'recovery' => '2.5 to 3 min easy jog',
        'intensity' => 'Around 12-minute target pace',
        'best_for' => 'Preparing the body to hold fast pace under fatigue',
        'note' => 'Advanced general session. If the runner cannot keep form, reduce to 3 reps.',
    ],
    [
        'id' => 'cooper12_3x1200_race_pressure',
        'goal' => 'COOPER_12_MIN_GENERAL',
        'type' => 'interval',
        'name' => '3 x 1.2K Race Pressure',
        'focus' => 'Pace tolerance',
        'main_set' => '3 reps x 1.2K',
        'recovery' => '3 min easy jog',
        'intensity' => 'Target 12-minute pace',
        'best_for' => 'Simulating the painful middle part of the Cooper test',
        'note' => 'Use in peak phase only. This workout is mentally and physically demanding.',
    ],
    [
        'id' => 'cooper12_20min_threshold',
        'goal' => 'COOPER_12_MIN_GENERAL',
        'type' => 'threshold',
        'name' => '20 Min Threshold Run',
        'focus' => 'Lactate threshold',
        'main_set' => '20 min continuous controlled hard run',
        'recovery' => 'No full recovery',
        'intensity' => 'Comfortably hard, slower than 12-minute test pace',
        'best_for' => 'Improving ability to clear fatigue and hold strong breathing',
        'note' => 'Do not turn this into a time trial. The goal is controlled pressure.',
    ],
    [
        'id' => 'cooper12_3x6min_threshold',
        'goal' => 'COOPER_12_MIN_GENERAL',
        'type' => 'threshold',
        'name' => '3 x 6 Min Threshold',
        'focus' => 'Aerobic strength',
        'main_set' => '3 reps x 6 min',
        'recovery' => '2 min easy jog',
        'intensity' => 'Threshold effort, around 85 to 90 percent effort',
        'best_for' => 'General runners who need stamina before harder intervals',
        'note' => 'Use in base or early build phase before heavy 800m and 1K workouts.',
    ],
    [
        'id' => 'cooper12_12x200_sharpening',
        'goal' => 'COOPER_12_MIN_GENERAL',
        'type' => 'repetition',
        'name' => '12 x 200m Sharpening',
        'focus' => 'Speed, cadence, and nervous system',
        'main_set' => '12 reps x 200m',
        'recovery' => '200m easy jog',
        'intensity' => 'Fast but relaxed, never all-out sprint',
        'best_for' => 'Taper week and speed maintenance',
        'note' => 'Use when the test is close and the runner needs freshness, not exhaustion.',
    ],
    [
        'id' => 'cooper12_hill_10x30sec',
        'goal' => 'COOPER_12_MIN_GENERAL',
        'type' => 'hill',
        'name' => '10 x 30 Sec Hill Repeats',
        'focus' => 'Power and running economy',
        'main_set' => '10 reps x 30 sec uphill',
        'recovery' => 'Walk down slowly',
        'intensity' => 'Strong but controlled',
        'best_for' => 'Building leg power with lower impact than flat sprinting',
        'note' => 'Keep posture tall. This is not a death sprint.',
    ],
    [
        'id' => 'cooper12_6min_4min_2min_simulation',
        'goal' => 'COOPER_12_MIN_GENERAL',
        'type' => 'simulation',
        'name' => '6 Min + 4 Min + 2 Min Simulation',
        'focus' => 'Cooper test pacing',
        'main_set' => '6 min at target pace + 3 min jog + 4 min slightly faster + 2 min jog + 2 min hard finish',
        'recovery' => 'Jog recovery between blocks',
        'intensity' => 'Progressive 12-minute race effort',
        'best_for' => 'Teaching the runner not to panic in the first half',
        'note' => 'Very useful 7 to 14 days before test day.',
    ],
    [
        'id' => 'cooper12_full_12min_time_trial',
        'goal' => 'COOPER_12_MIN_GENERAL',
        'type' => 'time_trial',
        'name' => '12 Min Cooper Time Trial',
        'focus' => 'Testing and pacing evaluation',
        'main_set' => '12 min maximal controlled run',
        'recovery' => 'Full recovery after session',
        'intensity' => 'Best sustainable effort for 12 minutes',
        'best_for' => 'Measuring progress toward 3200m and 3400m',
        'note' => 'Use every 3 to 4 weeks, not every week. Too frequent testing can destroy training quality.',
    ],
]
];
